project:
  type: website
  output-dir: docs

website:
  title: "15lucyhart"  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Resume.qmd
        text: Resume
      - href: www/LucyHartResume.pdf
        text: Resume PDF
      - href: Fountain.qmd
        text: Fountain Creek Watershed District
      - href: RockyMtn.qmd
        text: Rocky Mountain Ski and Sport
      - href: Snowboarding.qmd
        text: Snowboarding
      - href: Soccer.qmd
        text: Soccer
 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

